import React, { useState, useEffect, useRef } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { supabase } from '../config/supabaseConfig';
import Groq from 'groq-sdk';
import ReactMarkdown from 'react-markdown';
import HealaLoader from '../components/HealaLoader';

const apiKeys = [
    import.meta.env.VITE_GROQ_API_KEY,
    import.meta.env.VITE_GROQ_API_KEY_2,
    import.meta.env.VITE_GROQ_API_KEY_3
].filter(Boolean);

let currentKeyIndex = 0;
let groq = new Groq({
    apiKey: apiKeys[currentKeyIndex],
    dangerouslyAllowBrowser: true
});

const rotateGroqKey = () => {
    currentKeyIndex = (currentKeyIndex + 1) % apiKeys.length;
    groq = new Groq({
        apiKey: apiKeys[currentKeyIndex],
        dangerouslyAllowBrowser: true
    });
    console.log(`Switched to Groq API Key ${currentKeyIndex + 1}`);
};

const Chatbot = () => {
    const { user } = useAuth();
    const [sessions, setSessions] = useState([]);
    const [activeSessionId, setActiveSessionId] = useState(null);
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const [loading, setLoading] = useState(true);
    const [isSidebarOpen, setIsSidebarOpen] = useState(true);
    const messagesEndRef = useRef(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    };

    useEffect(() => {
        if (user) {
            fetchSessions();
        }
    }, [user]);

    useEffect(() => {
        if (activeSessionId) {
            fetchMessages(activeSessionId);
        }
    }, [activeSessionId]);

    useEffect(() => {
        scrollToBottom();
    }, [messages]);

    const fetchSessions = async () => {
        try {
            const { data, error } = await supabase
                .from('chat_sessions')
                .select('*')
                .eq('profile_id', user.id)
                .order('created_at', { ascending: false });

            if (error) throw error;
            setSessions(data || []);

            if (data && data.length > 0 && !activeSessionId) {
                setActiveSessionId(data[0].id);
            } else if (!data || data.length === 0) {
                createNewSession();
            }
        } catch (error) {
            console.error("Error fetching sessions:", error);
        } finally {
            setLoading(false);
        }
    };

    const fetchMessages = async (sessionId) => {
        try {
            const { data, error } = await supabase
                .from('chatbot_logs')
                .select('*')
                .eq('session_id', sessionId)
                .order('created_at', { ascending: true });

            if (error) throw error;
            if (data && data.length > 0) {
                setMessages(data.map(l => ({ role: l.role, content: l.message })));
            } else {
                setMessages([{
                    role: 'assistant',
                    content: `Hello! I am **Healia**, your personal health assistant. \n\nBefore we begin, may I know what your name is? \n\n --- \n\n > **⚠️ AI Health Guidance Disclaimer** \n > The responses generated by this AI system are intended for informational and educational purposes only. They do not constitute medical advice and should not be used as a substitute for professional healthcare consultation. \n\n > **Users must consult Healas Global specialists or licensed medical professionals before making any clinical or treatment decisions.**`
                }]);
            }
        } catch (error) {
            console.error("Error fetching messages:", error);
        }
    };

    const createNewSession = async () => {
        try {
            const { data, error } = await supabase
                .from('chat_sessions')
                .insert([{ profile_id: user.id, title: 'New Conversation' }])
                .select()
                .single();

            if (error) throw error;
            setSessions(prev => [data, ...prev]);
            setActiveSessionId(data.id);
            setMessages([{
                role: 'assistant',
                content: `Hello! I am **Healia**, your personal health assistant. \n\nBefore we begin, may I know what your name is? \n\n --- \n\n > **⚠️ AI Health Guidance Disclaimer** \n > The responses generated by this AI system are intended for informational and educational purposes only. They do not constitute medical advice and should not be used as a substitute for professional healthcare consultation. \n\n > **Users must consult Healas Global specialists or licensed medical professionals before making any clinical or treatment decisions.**`
            }]);
        } catch (error) {
            console.error("Error creating session:", error);
        }
    };

    const deleteSession = async (e, sessionId) => {
        e.stopPropagation();
        if (!window.confirm('Delete this conversation?')) return;

        try {
            const { error } = await supabase.from('chat_sessions').delete().eq('id', sessionId);
            if (error) throw error;

            setSessions(prev => prev.filter(s => s.id !== sessionId));
            if (activeSessionId === sessionId) {
                setActiveSessionId(null);
                const remaining = sessions.filter(s => s.id !== sessionId);
                if (remaining.length > 0) {
                    setActiveSessionId(remaining[0].id);
                } else {
                    createNewSession();
                }
            }
        } catch (error) {
            console.error("Error deleting session:", error);
        }
    };

    const handleSend = async (e) => {
        e.preventDefault();
        if (!input.trim() || isTyping || !activeSessionId) return;

        const userMsgContent = input;
        const userMessage = { role: 'user', content: userMsgContent };

        setMessages(prev => [...prev, userMessage]);
        setInput('');
        setIsTyping(true);

        try {
            // 1. Save user message
            await supabase.from('chatbot_logs').insert({
                profile_id: user.id,
                session_id: activeSessionId,
                message: userMsgContent,
                role: 'user'
            });

            // 2. Groq AI logic with Failover
            let chatCompletion;
            let attempts = 0;
            const maxAttempts = apiKeys.length;

            while (attempts < maxAttempts) {
                try {
                    chatCompletion = await groq.chat.completions.create({
                        messages: [
                            {
                                role: "system",
                                content: `You are Healia, a medical AI assistant from JS Corporations. 
                                Gobika Rangasamy is the MD(Managing Directors) of JS Corporations.
                                Jeevasurya is the Founder of JS Corporations.
                                JS Corporations was founded in 2025.
                                
                                Heala's Board Members include:
                                - Dr. Karthika (Chief Cardiologist)
                                - Dr. Mathumitha (Head of Diagnostics)
                                - Dr. Manju (Lead Pediatrician)
                                
                                **Brand Definitions**: 
                                - **Heala** is the name of the Company and the entire Health Platform.
                                - **Healia** is the specific name of you, the AI Chatbot.
                                
                                You are helpful, professional, and empathetic. 
                                Always prioritize patient safety.
                                If you do not know the user's name yet, your first priority is to discover it.
                                If the 'Current user' metadata is 'Guest' or generic, and it hasn't been provided in the conversation history, politely ask: "May I know your name before we proceed?"
                                NEVER assume the user is "JS". "JS" refers to the Founder (Jeevasurya).
                                Once you know the user's name, address them by it in every message.
                                **Formatting Rule**: Use frequent paragraph breaks (double newlines) to keep responses airy and easy to read. Never output walls of text.
                                Current user metadata is: ${user?.name || 'Guest'}.`
                            },
                            ...messages.map(m => ({ role: m.role, content: m.content })),
                            userMessage
                        ],
                        model: "llama-3.3-70b-versatile",
                    });
                    break; // Success!
                } catch (err) {
                    if (err.status === 429 && attempts < maxAttempts - 1) {
                        console.warn("Rate limit hit, rotating Groq API key...");
                        rotateGroqKey();
                        attempts++;
                    } else {
                        throw err; // Re-throw if not 429 or no more keys
                    }
                }
            }

            const assistantMsgContent = chatCompletion.choices[0]?.message?.content || "I couldn't process that.";
            const assistantMessage = { role: 'assistant', content: assistantMsgContent };

            // 3. Save assistant message
            await supabase.from('chatbot_logs').insert({
                profile_id: user.id,
                session_id: activeSessionId,
                message: assistantMsgContent,
                role: 'assistant'
            });

            setMessages(prev => [...prev, assistantMessage]);

            // 4. Update session title if it's the first exchange
            if (messages.length === 1) {
                const titleMatch = userMsgContent.substring(0, 30) + (userMsgContent.length > 30 ? '...' : '');
                await supabase.from('chat_sessions').update({ title: titleMatch }).eq('id', activeSessionId);
                setSessions(prev => prev.map(s => s.id === activeSessionId ? { ...s, title: titleMatch } : s));
            }

        } catch (error) {
            console.error("AI Error:", error);
            setMessages(prev => [...prev, { role: 'assistant', content: "I'm having trouble connecting. Please try again." }]);
        } finally {
            setIsTyping(false);
        }
    };

    if (loading) return <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><HealaLoader /></div>;

    return (
        <div style={{
            height: '100vh',
            background: '#faf5f5', // Soft champagne background
            display: 'flex',
            overflow: 'hidden',
            fontFamily: '"DM Sans", sans-serif',
            color: '#2d1b33' // Deep violet for text
        }}>
            {/* Premium Glass Sidebar */}
            <aside style={{
                width: isSidebarOpen ? '320px' : '0',
                background: 'rgba(255, 255, 255, 0.4)',
                backdropFilter: 'blur(25px)',
                borderRight: '1px solid rgba(241, 156, 187, 0.2)',
                transition: 'all 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
                display: 'flex',
                flexDirection: 'column',
                overflow: 'hidden',
                zIndex: 100,
                paddingTop: '80px',
                boxShadow: '10px 0 30px rgba(0,0,0,0.02)'
            }}>
                <div style={{ padding: '2rem' }}>
                    <button
                        onClick={createNewSession}
                        style={{
                            width: '100%', padding: '1.2rem', borderRadius: '18px',
                            background: 'linear-gradient(135deg, #f19cbb, #d946ef)',
                            border: 'none',
                            color: 'white', fontWeight: 900, fontSize: '0.9rem',
                            cursor: 'pointer', boxShadow: '0 10px 20px -5px rgba(241, 156, 187, 0.4)',
                            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px',
                            transition: 'transform 0.3s ease'
                        }}
                        onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-2px)'}
                        onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
                    >
                        <span style={{ fontSize: '1.2rem' }}>+</span> New Conversation
                    </button>
                </div>

                <div style={{ flex: 1, overflowY: 'auto', padding: '0 1rem 2rem' }} className="custom-scroll">
                    <p style={{ fontSize: '0.7rem', fontWeight: 900, color: '#f19cbb', letterSpacing: '2px', padding: '0 1rem 1rem', textTransform: 'uppercase', opacity: 0.8 }}>Recent Intelligence</p>
                    {sessions.map(s => (
                        <div
                            key={s.id}
                            onClick={() => setActiveSessionId(s.id)}
                            style={{
                                padding: '1rem 1.2rem', borderRadius: '16px', marginBottom: '0.6rem',
                                background: activeSessionId === s.id ? 'rgba(241, 156, 187, 0.1)' : 'transparent',
                                border: `1px solid ${activeSessionId === s.id ? 'rgba(241, 156, 187, 0.2)' : 'transparent'}`,
                                cursor: 'pointer', transition: 'all 0.3s ease',
                                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                                position: 'relative'
                            }}
                        >
                            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flex: 1, minWidth: 0 }}>
                                <span style={{ opacity: activeSessionId === s.id ? 1 : 0.4 }}>✨</span>
                                <span style={{ fontWeight: 700, fontSize: '0.9rem', color: activeSessionId === s.id ? '#d946ef' : '#2d1b33', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{s.title}</span>
                            </div>
                            <button
                                onClick={(e) => deleteSession(e, s.id)}
                                style={{ background: 'none', border: 'none', color: '#ef4444', opacity: 0, cursor: 'pointer', fontSize: '1rem', padding: '5px', transition: 'opacity 0.2s' }}
                                className="delete-btn"
                            >
                                ✕
                            </button>
                        </div>
                    ))}
                </div>
            </aside>

            {/* Main Chat Interface */}
            <main style={{ flex: 1, display: 'flex', flexDirection: 'column', position: 'relative', background: 'transparent', paddingTop: '80px' }}>
                {/* Chic Chat Header */}
                <header style={{
                    padding: '1.5rem 3.5rem',
                    background: 'rgba(255, 255, 255, 0.2)',
                    borderBottom: '1px solid rgba(241, 156, 187, 0.1)',
                    display: 'flex',
                    alignItems: 'center', gap: '1.5rem', backdropFilter: 'blur(15px)',
                    zIndex: 10
                }}>
                    <button
                        onClick={() => setIsSidebarOpen(!isSidebarOpen)}
                        style={{ background: 'white', border: '1px solid rgba(241, 156, 187, 0.3)', color: '#f19cbb', padding: '10px 14px', borderRadius: '12px', cursor: 'pointer', boxShadow: '0 4px 10px rgba(0,0,0,0.03)' }}
                    >
                        {isSidebarOpen ? '❮' : '❯'}
                    </button>
                    <div style={{ width: '50px', height: '50px', background: 'linear-gradient(135deg, #f19cbb, #d946ef)', borderRadius: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.4rem', color: 'white', boxShadow: '0 10px 20px rgba(241, 156, 187, 0.3)' }}>✨</div>
                    <div>
                        <h2 style={{ fontSize: '1.3rem', fontWeight: 900, margin: 0, color: '#2d1b33', fontFamily: 'Playfair Display, serif' }}>Healia Intelligence</h2>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                            <div style={{ width: '6px', height: '6px', background: '#10b981', borderRadius: '50%', boxShadow: '0 0 8px #10b981' }} />
                            <span style={{ fontSize: '0.75rem', color: '#10b981', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '1px' }}>Active Response Network</span>
                        </div>
                    </div>
                </header>

                {/* Messages Gallery */}
                <div style={{ flex: 1, overflowY: 'auto', padding: '2.5rem 10%', display: 'flex', flexDirection: 'column', gap: '2.5rem' }} className="custom-scroll">
                    <div style={{ textAlign: 'center', marginBottom: '4rem', padding: '4rem 2rem', opacity: messages.length > 1 ? 0.3 : 1, transition: 'opacity 0.5s' }}>
                        <span style={{ fontSize: '3rem', display: 'block', marginBottom: '1rem' }}>🌸</span>
                        <h1 style={{ fontFamily: 'Playfair Display, serif', fontSize: '2.5rem', color: '#2d1b33', margin: '0 0 1rem 0' }}>How can I assist your journey?</h1>
                        <p style={{ color: '#f19cbb', fontWeight: 600, letterSpacing: '2px', textTransform: 'uppercase', fontSize: '0.8rem' }}>AI Powered Medical Compass</p>
                    </div>

                    {messages.map((msg, i) => (
                        <div key={i} style={{
                            alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start',
                            maxWidth: '75%', display: 'flex', flexDirection: 'column', gap: '0.8rem',
                            animation: 'messageFlow 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards'
                        }}>
                            <div style={{
                                padding: '1.5rem 2rem',
                                borderRadius: msg.role === 'user' ? '30px 30px 5px 30px' : '30px 30px 30px 5px',
                                background: msg.role === 'user' ? '#f19cbb' : 'white',
                                color: msg.role === 'user' ? 'white' : '#2d1b33',
                                fontWeight: 500, fontSize: '1.05rem', lineHeight: '1.6',
                                border: msg.role === 'user' ? 'none' : '1px solid rgba(241, 156, 187, 0.1)',
                                boxShadow: msg.role === 'user' ? '0 15px 30px -10px rgba(241, 156, 187, 0.4)' : '0 10px 25px rgba(0,0,0,0.03)',
                                position: 'relative'
                            }} className="markdown-content">
                                <ReactMarkdown>{msg.content}</ReactMarkdown>
                                {msg.role !== 'user' && <div style={{ position: 'absolute', top: '-10px', left: '-10px', width: '30px', height: '30px', background: 'linear-gradient(135deg, #f19cbb, #d946ef)', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.8rem', color: 'white' }}>✨</div>}
                            </div>
                            <span style={{ fontSize: '0.65rem', color: '#f19cbb', fontWeight: 800, alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start', opacity: 0.6, letterSpacing: '1.5px', textTransform: 'uppercase' }}>
                                {msg.role === 'user' ? 'Visitor Inquiry' : 'Healia Resolution'}
                            </span>
                        </div>
                    ))}
                    {isTyping && (
                        <div style={{ alignSelf: 'flex-start', background: 'white', padding: '1.2rem 2rem', borderRadius: '25px', border: '1px solid rgba(241, 156, 187, 0.1)', boxShadow: '0 10px 25px rgba(0,0,0,0.02)' }}>
                            <div style={{ display: 'flex', gap: '8px' }}>
                                {[1, 2, 3].map(d => <div key={d} style={{ width: '8px', height: '8px', background: '#f19cbb', borderRadius: '50%', animation: 'bounce 1.4s infinite ease-in-out', animationDelay: `${d * 0.2}s` }} />)}
                            </div>
                        </div>
                    )}
                    <div ref={messagesEndRef} />
                </div>

                {/* Aesthetic Command Center */}
                <div style={{ padding: '2rem 10%', background: 'transparent' }}>
                    <form onSubmit={handleSend} style={{
                        background: 'white',
                        border: '1px solid rgba(241, 156, 187, 0.3)',
                        borderRadius: '28px', padding: '0.6rem', display: 'flex', gap: '0.8rem',
                        boxShadow: '0 25px 50px -15px rgba(241, 156, 187, 0.15)',
                        transition: 'all 0.3s ease'
                    }} className="input-focus-effect">
                        <input
                            value={input}
                            onChange={(e) => setInput(e.target.value)}
                            placeholder="Type your health inquiry..."
                            style={{
                                flex: 1, background: 'transparent', border: 'none',
                                padding: '1.2rem 1.8rem', color: '#2d1b33', fontSize: '1rem',
                                fontWeight: '600', outline: 'none'
                            }}
                        />
                        <button
                            type="submit"
                            disabled={isTyping}
                            style={{
                                width: '60px', height: '60px', background: '#f19cbb',
                                color: 'white', borderRadius: '22px', border: 'none',
                                fontWeight: '900', cursor: 'pointer', transition: 'all 0.3s ease',
                                display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem',
                                boxShadow: '0 8px 15px rgba(241, 156, 187, 0.3)'
                            }}
                        >
                            <span style={{ transform: 'rotate(-45deg)', display: 'inline-block' }}>✈</span>
                        </button>
                    </form>
                    <p style={{ textAlign: 'center', fontSize: '0.75rem', color: '#f19cbb', marginTop: '1.5rem', fontWeight: 700, opacity: 0.8, letterSpacing: '0.5px' }}>
                        AI Guidance System • Heala Enhanced by JS • Always consult
                        <span style={{ color: '#d946ef' }}> Healas Global Specialists </span>
                        for clinical decisions.
                    </p>
                </div>
            </main>

            <style>{`
                @keyframes bounce { 0%, 80%, 100% { transform: scale(0); } 40% { transform: scale(1.0); } }
                @keyframes messageFlow { from { opacity: 0; transform: translateY(15px); } to { opacity: 1; transform: translateY(0); } }
                
                .custom-scroll::-webkit-scrollbar { width: 6px; }
                .custom-scroll::-webkit-scrollbar-track { background: transparent; }
                .custom-scroll::-webkit-scrollbar-thumb { background: rgba(241, 156, 187, 0.2); borderRadius: 10px; }
                
                .markdown-content p { margin-bottom: 1.2rem; }
                .markdown-content p:last-child { margin-bottom: 0; }
                .markdown-content ul, .markdown-content ol { margin: 1rem 0; padding-left: 1.2rem; }
                .markdown-content strong { color: #d946ef; font-weight: 800; }
                
                .input-focus-effect:focus-within {
                    border-color: #f19cbb !important;
                    box-shadow: 0 30px 60px -20px rgba(241, 156, 187, 0.3) !important;
                    transform: translateY(-2px);
                }
                
                aside div:hover .delete-btn { opacity: 0.6 !important; }
                .delete-btn:hover { opacity: 1 !important; transform: scale(1.2); }
            `}</style>
        </div>
    );
};

export default Chatbot;
